#ifndef _COMMON_BIT_SET_H_
#define _COMMON_BIT_SET_H_

#define SET_BIT_X_TO_1(BIT) (1<<BIT)
#define SET_BIT_X_TO_0(BIT) ~SET_BIT_X_TO_1(BIT)

#define SET_ITS_BIT_X_TO_1(VALUE,BIT) (VALUE|=SET_BIT_X_TO_1(BIT))
#define SET_ITS_BIT_X_TO_0(VALUE,BIT) (VALUE&=SET_BIT_X_TO_0(BIT))
#endif// _COMMON_BIT_SET_H_
