set_property IOSTANDARD LVCMOS12 [get_ports {led[*]}]
set_property PACKAGE_PIN B5 [get_ports {led[3]}]
set_property PACKAGE_PIN A5 [get_ports {led[2]}]
set_property PACKAGE_PIN D6 [get_ports {led[1]}]
set_property PACKAGE_PIN D5 [get_ports {led[0]}]
